export { default as Clients } from './clients/clients'
export { default as Service } from './service/service'
export { default as Navbar } from './navbar/navbar'
export { default as Formbtn } from './formbtn/formbtn'
export { default as Servicecard } from './servicecard/servicecard'
export { default as Banner } from './banner/banner'
export { default as Fnservice } from './fnservice/fnservice'
